services:
  backend:
    build:
      context: ./backend
    container_name: backend_cont
    volumes:
      - ./backend:/app
    networks:
      - aio_mlops_net
    ports:
      - 8000:8000
    entrypoint: "uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: ./
    container_name: frontend_cont
    env_file:
      - ./.env
    networks:
      - aio_mlops_net
    ports:
      - 3000:3000
    entrypoint: "pnpm run dev"

networks:
  aio_mlops_net:
    driver: bridge